from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def build_report_json(assessment, assets) -> dict:
    return {
        "report_version": "1.0",
        "pci_dss_version": assessment.pci_dss_version,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "organization": assessment.organization,
        "assessment_name": assessment.name,
        "assets": [
            {
                "id": a.id,
                "name": a.name,
                "ip_address": a.ip_address,
                "hostname": a.hostname,
                "asset_type": a.asset_type,
                "scope_status": a.scope_status,
                "is_cde": a.is_cde,
                "stores_pan": a.stores_pan,
                "processes_pan": a.processes_pan,
                "transmits_pan": a.transmits_pan,
                "justification": a.justification,
                "segmentation_notes": a.segmentation_notes,
                "tags": a.tags or [],
            }
            for a in assets
        ],
    }


def build_pdf(report) -> bytes:
    import io

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=18, spaceAfter=6)
    h2_style = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=12, spaceAfter=4)
    normal = styles["Normal"]

    rj = report.report_json or {}
    story.append(Paragraph("PCI DSS Scope Confirmation Report", title_style))
    story.append(Paragraph(f"Organization: {rj.get('organization', 'N/A')}", normal))
    story.append(Paragraph(f"Assessment: {rj.get('assessment_name', 'N/A')}", normal))
    story.append(Paragraph(f"PCI DSS Version: {rj.get('pci_dss_version', '4.0')}", normal))
    story.append(Paragraph(f"Generated: {rj.get('generated_at', '')}", normal))
    story.append(Spacer(1, 8 * mm))

    summary = report.summary or {}
    story.append(Paragraph("Scope Summary", h2_style))
    summary_data = [
        ["Category", "Count"],
        ["In-Scope (CDE)", str(summary.get("in_scope", 0))],
        ["Connected-to-CDE", str(summary.get("connected", 0))],
        ["Out-of-Scope", str(summary.get("out_of_scope", 0))],
        ["Pending Review", str(summary.get("pending", 0))],
        ["Total Assets", str(summary.get("total", 0))],
    ]
    t = Table(summary_data, colWidths=[120 * mm, 40 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
    ]))
    story.append(t)
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph("Asset Inventory", h2_style))
    asset_data = [["Name", "IP / Hostname", "Type", "Scope Status", "CDE", "Justification"]]
    for a in rj.get("assets", []):
        location = a.get("ip_address") or a.get("hostname") or "—"
        asset_data.append([
            a.get("name", ""),
            location,
            a.get("asset_type", "").replace("_", " ").title(),
            a.get("scope_status", "").replace("_", " ").title(),
            "Yes" if a.get("is_cde") else "No",
            (a.get("justification") or "")[:60],
        ])
    at = Table(asset_data, colWidths=[35 * mm, 35 * mm, 25 * mm, 30 * mm, 12 * mm, 33 * mm])
    at.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(at)

    story.append(Spacer(1, 12 * mm))
    story.append(Paragraph(
        "This report was generated by the PCI DSS Scoping Tool and should be reviewed by a "
        "Qualified Security Assessor (QSA) before use in a formal assessment. "
        f"PCI DSS v{rj.get('pci_dss_version', '4.0')} — Requirement 12.3 compliance documentation.",
        ParagraphStyle("footer", parent=normal, fontSize=7, textColor=colors.grey),
    ))

    doc.build(story)
    return buf.getvalue()
